<?php

return [
    'overall' => [
        ["images/gallery/refinishing/1a.jpeg", "images/gallery/refinishing/1b.jpeg"],
        ["images/gallery/refinishing/2a.jpeg", "images/gallery/refinishing/2b.jpeg"],
        ["images/gallery/refinishing/3a.jpeg", "images/gallery/refinishing/3b.jpeg"],
        ["images/gallery/refinishing/4a.jpeg", "images/gallery/refinishing/4b.jpeg"],
        ["images/gallery/refinishing/5a.jpeg", "images/gallery/refinishing/5b.jpeg"],
        ["images/gallery/refinishing/6a.jpeg", "images/gallery/refinishing/6b.jpeg"],
        ["images/gallery/refinishing/7a.jpeg", "images/gallery/refinishing/7b.jpeg"],
        ["images/gallery/refinishing/8a.jpeg", "images/gallery/refinishing/8b.jpeg"],
        ["images/gallery/refinishing/9a.jpeg", "images/gallery/refinishing/9b.jpeg"],
        ["images/gallery/refinishing/10a.jpeg", "images/gallery/refinishing/10b.jpeg"],
        ["images/gallery/refinishing/11a.jpeg", "images/gallery/refinishing/11b.jpeg"],
        ["images/gallery/refinishing/12a.jpeg", "images/gallery/refinishing/12b.jpeg"],
        ["images/gallery/refinishing/13a.jpeg", "images/gallery/refinishing/13b.jpeg"],
        ["images/gallery/refinishing/14a.jpeg", "images/gallery/refinishing/14b.jpeg"],
        ["images/gallery/refinishing/15a.jpeg", "images/gallery/refinishing/15b.jpeg"],
        ["images/gallery/refinishing/16a.jpeg", "images/gallery/refinishing/16b.jpeg"],
        ["images/gallery/refinishing/17a.jpeg", "images/gallery/refinishing/17b.jpeg"],
        ["images/gallery/refinishing/18a.jpeg", "images/gallery/refinishing/18b.jpeg"],
        ["images/gallery/refinishing/19a.jpeg", "images/gallery/refinishing/19b.jpeg"],
        ["images/gallery/refinishing/20a.jpeg", "images/gallery/refinishing/20b.jpeg"],
        ["images/gallery/refinishing/21a.jpeg", "images/gallery/refinishing/21b.jpeg"],
        ["images/gallery/refinishing/22a.jpeg", "images/gallery/refinishing/22b.jpeg"],
        ["images/gallery/refinishing/23a.jpeg", "images/gallery/refinishing/23b.jpeg"],
        ["images/gallery/re-dooring/1a.jpeg", "images/gallery/re-dooring/1b.jpeg"],
        ["images/gallery/re-dooring/2a.jpeg", "images/gallery/re-dooring/2b.jpeg"],
        ["images/gallery/re-dooring/3a.jpeg", "images/gallery/re-dooring/3b.jpeg"],
        ["images/gallery/re-dooring/4a.jpeg", "images/gallery/re-dooring/4b.jpeg"],
        ["images/gallery/re-dooring/5a.jpeg", "images/gallery/re-dooring/5b.jpeg"],
        ["images/gallery/re-dooring/6a.jpeg", "images/gallery/re-dooring/6b.jpeg"],
        ["images/gallery/re-dooring/7a.jpeg", "images/gallery/re-dooring/7b.jpeg"],
        ["images/gallery/re-dooring/8a.jpeg", "images/gallery/re-dooring/8b.jpeg"],
        ["images/gallery/re-dooring/9a.jpeg", "images/gallery/re-dooring/9b.jpeg"],
        ["images/gallery/custom-finishes/1.jpeg"],
        ["images/gallery/custom-finishes/2.jpeg"],
    ],
];